### PR TITLE
V2 Signing

### PR DESCRIPTION
**Pull request by janmarcano**
`AlgoSigner.signTxn()` will receive an array of encoded transactions in the form of:

```
{
  txn: base64 encoded msgpack of the transaction;
};
```
**If multiple transactions are provided, they need to all belong to the same group. Otherwise, you need sign them one by one.**

Helpers where added to the AlgoSigner object to help with encoding and decoding base64 strings into and from msgpack. These are:

```
AlgoSigner.encoding.msgpackToBase64(...);
AlgoSigner.encoding.base64ToMsgpack(...);
```

An example of all working together would be:
```
await AlgoSigner.connect();
let client = new algosdk.Algodv2(...);

let testNetParams = await client.getTransactionParams().do();
testNetParams.flatFee = true;

let tx1 = new algosdk.Transaction({
  to: "SZWKCKKD3ZJWFABPHN7SLSZUDEHHTE3L5SUZ4KIZ4NS45GOYFW5QTZ3C74",
  from: "SZWKCKKD3ZJWFABPHN7SLSZUDEHHTE3L5SUZ4KIZ4NS45GOYFW5QTZ3C74",
  amount: 1,
  ...testNetParams,
});

let tx2 = new algosdk.Transaction({
  to: "VUJRANZJWWGS4FXZGZLZFQ2XGRPXOPWO4H5N4YDRFZS3USH3VBGJ3QKE6U",
  from: "VUJRANZJWWGS4FXZGZLZFQ2XGRPXOPWO4H5N4YDRFZS3USH3VBGJ3QKE6U",
  amount: 1,
  ...testNetParams,
});

algosdk.assignGroupID([tx1, tx2]);

let sdkTxs = [tx1, tx2];
let base64Txs = sdkTxs.map((tx) => {
  return AlgoSigner.encoding.msgpackToBase64(tx.toByte());
});
let walletTxs = base64Txs.map((b64) => {
  return { txn: b64 };
});

let signedTxs = await AlgoSigner.signTxn(walletTxs);

let sendResult = await client
  .sendRawTransaction(
    signedTxs.map((signedTx) =>
      AlgoSigner.encoding.base64ToMsgpack(signedTx.blob)
    )
  )
  .do();
```

Approval needed
After approval

### CODE REVIEW

**Comment by robert-zaremba** [comment]
Hi. When this PR will be merged and released? Recently, at Algo Builder, we started the integration with AlgoSigner. Our libraries depend heavily on V2 signing, so this PR is very much needed!

**Comment by janmarcano** [comment]
@robert-zaremba we're aiming for v2 signing to go out with the 1.5.0 release :)

**Comment by robert-zaremba** [comment]
What's the ETA for 1.5?

**Comment by janmarcano** [comment]
@robert-zaremba hi Robert, we had some backs-and-forths with the people at the Algorand Foundation, which delayed the work on v2 a bit, since we wanted to comply with the new Foundation standard that was developed for future wallets. We're aiming on 1.5 to be the next release, and that should happen between this week and the next one

**Comment by robert-zaremba** [comment]
Thank you for the update @janmarcano !

**Review by PureBrent — APPROVED** [review]

**Review by fxgamundi — APPROVED** [review]

**Pull request merged**
